sudo: required

matrix:
  include:
    # Sonar scan
    - language: go
      go:
        - 1.12
      addons:
        sonarcloud:
          organization: "thecampagnards-github"
      cache:
        directories:
          - "$HOME/.sonar/cache"
          - "$GOPATH/pkg/dep"
          - "client/node_modules"
      go_import_path: docktor
      install:
        - git fetch --unshallow --quiet
        - npm link typescript
        - go get -u github.com/golang/dep/cmd/dep
      script:
        - cd client
        - npm install
        - npm run test
        - cd ..
        - cd server
        - dep ensure -v
        - go test ./... -coverprofile="coverage.out"
        - cd ..
        - sonar-scanner -Dsonar.go.coverage.reportPaths="server/coverage.out" -Dsonar.typescript.lcov.reportPaths="client/coverage/lcov.info"
    # Docker build
    - language: sh
      services:
        - docker
      before_install:
        - DOCKER_BASE="$DOCKER_USERNAME/docktor"
        - DOCKER_BUILDS=""
        - TAGS=""
        - test "$TRAVIS_BRANCH" = master && TAGS="$TAGS latest" || true
        - test -n "$TRAVIS_TAG"          && TAGS="$TAGS stable $TRAVIS_TAG" || true
        - echo "Tags are $TAGS"
      script:
        - docker build -t "$DOCKER_BASE:current" .
        - name="$DOCKER_BASE"
        - DOCKER_BUILDS="$DOCKER_BUILDS $name"
      after_success:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - |
          for repo in $DOCKER_BUILDS; do
            for tag in $TAGS; do
              echo "Deploying $repo:current as $repo:$tag...";
              docker tag "$repo:current" "$repo:$tag" || exit 1;
              docker push "$repo:$tag" || exit 1;
            done;
          done;
