version: '3'

services: 
  docktor:
    image: thecampagnards/docktor
    networks:
      - docktor_net
    ports: 
      - 8080:8080 
    environment:
      - MONGOHQ_URL=mongodb:27017
  mongodb:
    image: mongo
    networks:
       - docktor_net
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

networks:
  docktor_net: