version: '3'

services:
  docktor:
    image: thecampagnards/docktor
    networks:
      - docktor_net
    ports:
      - 8080:8080
    environment:
      - MONGO_URL=mongodb:27017
      - PRODUCTION=true
      - LOG_LEVEL=debug
      - DEFAULT_ADMIN_ACCOUNT=root
      - DEFAULT_ADMIN_PASSWORD=mysecretpassword
      - JWT_SECRET=NIi57BYu9kSZg3l47erj8hbzyiTQBwUnSuJ632OB
      - CRON_REFRESH=@every 30m
  mongodb:
    image: mongo
    networks:
       - docktor_net
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

networks:
  docktor_net: