version: "2"

services:
  watchtower:
    network_mode: bridge
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dicdk/users/cdksystem/.docker/config.json:/config.json:ro
    command: --label-enable
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  default:
    external:
      name: none