[[constraint]]
  name = "github.com/docker/libcompose"
  branch = "master"

[[constraint]]
  name = "github.com/docker/docker"
  revision = "0ede01237c9ab871f1b8db0364427407f3e46541"

[[override]]
  name = "github.com/docker/cli"
  version = "^18.09.6"

[[override]]
  name = "github.com/docker/distribution"
  version = "^2.7.1"

[[override]]
  name = "github.com/xeipuuv/gojsonschema"
  revision = "93e72a773fade158921402d6a24c819b48aba29d"

[[override]]
  name = "github.com/Nvveen/Gotty"
  revision = "6018b68f96b839edfbe3fb48668853f5dbad88a3"
  source = "github.com/ijc/Gotty"

[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.3.10"

[[constraint]]
  branch = "master"
  name = "github.com/globalsign/mgo"

[[constraint]]
  name = "github.com/google/cadvisor"
  version = "v0.33.1"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "v3.2.0"

[[constraint]]
  name = "gopkg.in/ldap.v3"
  version = "v3.0.3"

[[constraint]]
  name = "github.com/namsral/flag"
  revision = "67f268f20922975c067ed799e4be6bacf152208c"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "v1.4.2"

[[constraint]]
  name = "github.com/robfig/cron"
  version="v1.2.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "v1.3.0"

[[constraint]]
  name = "golang.org/x/net"
  revision = "9f648a60d9775ef5c977e7669d1673a7a67bef33"

[prune]
  go-tests = true
  unused-packages = true
