[[constraint]]
  name = "github.com/docker/libcompose"
  branch = "master"

[[constraint]]
  name = "github.com/docker/docker"
  revision = "0ede01237c9ab871f1b8db0364427407f3e46541"

[[override]]
  name = "github.com/docker/cli"
  version = "^18.09.3"

[[override]]
  name = "github.com/docker/distribution"
  version = "^2.7.1"

[[override]]
  name = "github.com/xeipuuv/gojsonschema"
  revision = "93e72a773fade158921402d6a24c819b48aba29d"

[[override]]
  name = "github.com/Nvveen/Gotty"
  revision = "6018b68f96b839edfbe3fb48668853f5dbad88a3"
  source = "github.com/ijc/Gotty"

[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.3.8"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "github.com/globalsign/mgo"

[[constraint]]
  name = "github.com/google/cadvisor"
  version = "v0.33.1"

[prune]
  go-tests = true
  unused-packages = true
